pages:
  stage: deploy
  image: ruby:2.3
  script:
    - gem install jekyll
    - jekyll build -d public/
    - cp ./public/.well-known/acme-challenge/-q3kHuFJivq_QTk_XRTadqf0nT7YHjCvY95Du61tKn0.html ./public/.well-known/acme-challenge/-q3kHuFJivq_QTk_XRTadqf0nT7YHjCvY95Du61tKn0
  artifacts:
    paths:
      - public
  only:
    - master
