
image: node:latest
cache:
  paths:
  - node_modules/
pages:
  script:
    - yarn install
    - ./node_modules/.bin/gatsby build --prefix-paths 
    - mkdir -p public/.well-known/acme-challenge/
  artifacts:
    paths:
    - public
  script: 
    - cp le/*  public/.well-known/acme-challenge/
  only:
  - master
