pages:
  stage: deploy
  image: ruby:2.3
  script:
    - gem install jekyll
    - jekyll build -d public/
    - cp ./public/.well-known/acme-challenge/pxAtgCRiIvd8TyA7UnE341bfu84SvvANTKhn4F4H8Ws.html ./public/.well-known/acme-challenge/pxAtgCRiIvd8TyA7UnE341bfu84SvvANTKhn4F4H8Ws
  artifacts:
    paths:
      - public
  only:
    - master
