pages:
  stage: deploy
  image: ruby:2.3
  script:
    - gem install jekyll
    - jekyll build -d public/
    - cp ./public/.well-known/acme-challenge/m9tzIDubrLWQg83ESp5ZHJylZWnN9UaF2w8q-6EO4eU.html ./public/.well-known/acme-challenge/m9tzIDubrLWQg83ESp5ZHJylZWnN9UaF2w8q-6EO4eU
  artifacts:
    paths:
      - public
  only:
    - master
