pages:
  stage: deploy
  image: ruby:2.3
  script:
    - gem install jekyll
    - jekyll build -d public/
    - cp ./public/.well-known/acme-challenge/4O7sRYYdtpgeiHQbiIeNjX1pGMv0r3ONivqLbnIYcc0.html ./public/.well-known/acme-challenge/4O7sRYYdtpgeiHQbiIeNjX1pGMv0r3ONivqLbnIYcc0
  artifacts:
    paths:
      - public
  only:
    - master
