# Site settings
title: Amr Elsekilly | Front-end Web Developer
email: amr@webee.com.mt
url: https://amrsekilly.com
hireurl: https://www.upwork.com/o/profiles/users/_~014d7603bde62ae128/
description: "Amr Mohamed Elsayed Elsekilly, Front-end web developer at Webee.com.mt"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  primary-blue: '#227DC4'
  secondary-blue: '#0e4369'
  links: '#ffffff'

# Social networks
social:
  - title: envelope
    url: mailto:amr@webee.com.mt
    name: Email
  - title: twitter
    url: https://twitter.com/amrsekilly
    name: Twitter
  - title: github
    url: https://github.com/amrsekilly
    name: GitHub
  - title: linkedin
    url: https://eg.linkedin.com/in/amrsekilly
    name: LinkedIn
  - title: instagram
    url: https://www.instagram.com/amrsekilly
    name: Instagram
  - title: facebook
    url: https://www.facebook.com/amrsekilly
    name: Facebook

# Build settings
# Sass
sass:
    style: compressed
markdown: kramdown
permalink: pretty


# My Projects' details
projects:
  - title: storageos
    name: StorageOS App
    url: https://storageos.com/
    large-image: /resources/showcase/storageos.png
    small-image: /resources/showcase/storageos-sm.png
    image-alt: StorageOS mock image
    date: 2016-2017
    country: UK
    occupation: Front-end Web Developer at <a href="http://webee.com.mt/">Webee</a>
    about: I worked on the front-end of phase-2 of that app along with two other front-end developers at <a href="http://webee.com.mt/">Webee</a>
    tech:
      - title: react
        name: React.js
        url: https://facebook.github.io/react/
      - title: redux
        name: Redux
        url: http://redux.js.org/
      - title: imm
        name: Immutable.js
        url: https://facebook.github.io/immutable-js/
      - title: sass
        name: Sass
        url: http://sass-lang.com/
      - title: gulp
        name: Gulp
        url: http://gulpjs.com/
      - title: git
        name: Git
        url: https://git-scm.com/
      - title: heroku
        name: Heroku
        url: https://www.heroku.com/

  - title: discoverly
    name: Discoverly App
    url: http://discoverly.ca/
    large-image: /resources/showcase/discoverly.png
    small-image: /resources/showcase/discoverly-sm.png
    image-alt: Discoverly mock image
    date: 2016
    country: CA
    occupation: Freelance Front-end Web Developer at <a href="https://www.freelancer.com/u/amrsekilly.html">Freelancer.com</a>
    about: I've converted the PSD to HTML5, then integrated that to an Angular 1.5 app I wrote for the given mock RESTful APIs. Another developer took over to integrate that to the production backend
    tech:
      - title: angular
        name: Angular.js 1.5
        url: https://angularjs.org/
      - title: rest
        name: RESTful APIs
        url: https://en.wikipedia.org/wiki/Representational_state_transfer
      - title: html
        name: HTML5
        url: https://www.w3.org/TR/html5/
      - title: less
        name: Less
        url: http://lesscss.org/
      - title: grunt
        name: Grunt
        url: http://gruntjs.com/
      - title: git
        name: Git
        url: https://git-scm.com/

  - title: aquaphoton
    name: Aquaphoton's Website
    url: http://aquaphoton.net/
    large-image: /resources/showcase/aquaphoton.png
    small-image: /resources/showcase/aquaphoton-sm.png
    image-alt: Aquaphoton's Website's mock image
    date: 2015
    country: EG
    occupation: Freelance Front-end Web Developer
    about: It was my first project. I've designed the website from scratch and converted it to HTML5
    tech:
      - title: handlebars
        name: Handlebars.js
        url: http://handlebarsjs.com/
      - title: html
        name: HTML5
        url: https://www.w3.org/TR/html5/
      - title: less
        name: Less
        url: http://lesscss.org/
      - title: grunt
        name: Grunt
        url: http://gruntjs.com/
      - title: git
        name: Git
        url: https://git-scm.com/
