# Site settings
title: Amr Elsekilly | Front-end Web Developer, HTML5, JavaScript, CSS3, Angular.js, Meteor.js
email: amr.e.dev@gmail.com
url: http://amrsekilly.com
description: "Amr Mohamed Elsayed Abdelkhalek Elsekilly, Front-end web developer, HTML5, JavaScript, CSS3, Angular.js, Meteor.js, ROV, MIA, Aquaphoton academy team, MATE"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#ffffff'

# Footer settings
footer: <a href="https://twitter.com/amrsekilly">Amr Sekilly</a>

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/amrsekilly
  - title: github
    url: https://github.com/amrme
  - title: linkedin
    url: https://eg.linkedin.com/in/amrsekilly
  - title: instagram
    url: https://www.instagram.com/amrsekilly
  - title: facebook
    url: https://www.facebook.com/amrsekilly

# Build settings
# Sass
sass:
    style: compressed
markdown: kramdown
permalink: pretty
