# Site settings
title: Amr Elsekilly | Front-end Web Developer
email: amr@webee.com.mt
url: https://amrsekilly.com
description: "Amr Mohamed Elsayed Elsekilly, Front-end web developer at Webee.com.mt"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  primary-blue: '#227DC4'
  secondary-blue: '#0e4369'
  links: '#ffffff'

# Social networks
social:
  - title: envelope
    url: mailto:amr@webee.com.mt
    name: Email
  - title: twitter
    url: https://twitter.com/amrsekilly
    name: Twitter
  - title: github
    url: https://github.com/amrsekilly
    name: GitHub
  - title: linkedin
    url: https://eg.linkedin.com/in/amrsekilly
    name: LinkedIn
  - title: instagram
    url: https://www.instagram.com/amrsekilly
    name: Instagram
  - title: facebook
    url: https://www.facebook.com/amrsekilly
    name: Facebook

# Build settings
# Sass
sass:
    style: compressed
markdown: kramdown
permalink: pretty
