# Site settings
title: Amr Elsekilly | Front-end Web Developer
email: amr@webee.com.mt
url: https://amrsekilly.com
description: "Amr Mohamed Elsayed Elsekilly, Front-end web developer at Webee.com.mt"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  primary-blue: '#227DC4'
  secondary-blue: '#0e4369'
  links: '#ffffff'

# Social networks
social:
  - title: envelope
    url: mailto:amr@webee.com.mt
    name: Email
  - title: twitter
    url: https://twitter.com/amrsekilly
    name: Twitter
  - title: github
    url: https://github.com/amrsekilly
    name: GitHub
  - title: linkedin
    url: https://eg.linkedin.com/in/amrsekilly
    name: LinkedIn
  - title: instagram
    url: https://www.instagram.com/amrsekilly
    name: Instagram
  - title: facebook
    url: https://www.facebook.com/amrsekilly
    name: Facebook

# My Projects' details
projects:
  - title: storageos
    name: StorageOS
    url: https://storageos.com/
    large-image: /resources/showcase/storageos.png
    small-image: /resources/showcase/storageos-sm.png
    image-alt: StorageOS mock image
    date: 2016-2017
    country: UK
    occupation: Front-end Web Developer at <a href="http://webee.com.mt/">Webee</a>
    about: I worked on the front-end of phase-2 of that app along with two other front-end developers at <a href="http://webee.com.mt/">Webee</a>
    tech:
      - title: react
        name: React.js
        url: https://facebook.github.io/react/
      - title: redux
        name: Redux
        url: http://redux.js.org/
      - title: imm
        name: Immutable.js
        url: https://facebook.github.io/immutable-js/
      - title: sass
        name: Sass
        url: http://sass-lang.com/
      - title: gulp
        name: Gulp
        url: http://gulpjs.com/
      - title: git
        name: Git
        url: https://git-scm.com/
      - title: heroku
        name: Heroku
        url: https://www.heroku.com/


# Build settings
# Sass
sass:
    style: compressed
markdown: kramdown
permalink: pretty
